name: Terraform Plan

on: [push, workflow_dispatch]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    uses: StephenDryden/workflow/.github/workflows/terraform-plan.yaml@main
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
