name: Destroy

on: [workflow_dispatch]

env:
  AWS_REGION: "eu-west-1"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github
          role-session-name: github
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Destroy
        id: plan
        run: terraform destroy --auto-approve
        continue-on-error: false
