name: cicd

on:
  workflow_dispatch:
  pull_request:
  push: { branches: [main] }

env:
  AWS_REGION: "eu-west-1"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required to update the pull request with the plan
  issues: write # This is required to create issues

jobs:
  build:
    uses: StephenDryden/workflow/.github/workflows/goterraform.yaml@main
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
