name: Terraform apply

on: [workflow_dispatch]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    uses: StephenDryden/workflow/.github/workflows/terraform-apply.yaml@main
