name: Terraform Destroy

on: [workflow_dispatch]

env:
  AWS_REGION: "eu-west-1"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    uses: StephenDryden/workflow/.github/workflows/terraform-destroy.yaml@main
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
